### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#10]
All the docs!

Things are coming along well, but I'd love help keeping things documented. There are three primary sources for docs:

- Hackage docs
- Tutorials/Guides
- Readme overviews of extensions/systems/concepts

Here're a few docs that need some love, any help is definitely appreciated!

- [x] [Installation/setup](https://github.com/ChrisPenner/rasa/blob/master/docs/Building-An-Extension.md)
- [x] [Building a basic extension](https://github.com/ChrisPenner/rasa/blob/master/docs/Building-An-Extension.md)
- [x] Keymap customization
- [x] [User configuration](https://github.com/ChrisPenner/rasa/tree/master/rasa-example-config) tutorial/overview
- [x] Rendering overview (how it works, how to write your own).
- [x] Extension style-guide, best practices in building composable and modular extensions.

**Comment by jasonm23** [comment]
If you have writing prompts that drill down another level from the check box tasks in the issue description, it will help encourage contribution.
