### ISSUE TITLE
Asynchronous Extensions

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#11]
Right now Rasa is completely synchronous with the exception of asynchronous event-listeners, this is simply because it's all new and we want to move fast; I've built in a small
escape hatch for adding more asynchronous support [here](https://github.com/ChrisPenner/rasa/blob/master/rasa/src/Rasa.hs#L47), 

Going forward we'll definitely need a stronger model for asynchronousity to prevent unnecessary pauses/blocking when performing things like syntax highlighting.

There are many possible models for this, and I'd love to hear about your thoughts!

**Comment by ChrisPenner** [comment]
One idea that would be quite simple to implement and would leave most of the
power with the extension would be to provide a `doAsync` action:

```haskell
doAsync :: IO (Action ()) -> Action ()
```

Which takes a definition of some computations (note that it takes an IO and not
an Action, this means that none of these computations can change any
buffers/text in their execution, but since the doAsync call will be run inside
an action details about the current state of the buffers at kick-off time can
be baked into the IO via a closure.

`doAsync` will store any queued actions in a list and when the action is `run`
it will collect the queue and kick them off asynchronously. The IO's have an
`Action ()` as their return value, so once the IO is complete then they can
(synchronously) enact any changes they've calculated during the async period,
or, if the buffer is in a different state than they expected (e.g. the text has
changed substantially) they may choose to disregard their computations,
schedule another `doAsync` call, partially apply the results, or just give up
entirely.

**Comment by ChrisPenner** [comment]
Possibly we could use some sort of [Continuation Monad](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Cont.html)

**Comment by mitchellwrosen** [comment]
I think ideally an extension writer should have full control over spawning/awaiting, `async` style. That is, I should be able to write

```haskell
myExtension = do
  ax <- spawn thing1
  ay <- spawn thing2
  x <- await ax
  y <- await ay
  go x y
```

The dynamics would be such that `spawn` spawns a green thread and returns immediately, whereas `await` yields control to the event loop and is resumed when `spawn thing1` completes. I haven't really puzzled out how this would work, but I think it'd be more involved than a single `ContT` somewhere in `Action`, or a `doAsync`-block.

**Comment by ChrisPenner** [comment]
That would definitely be a really nice model to work with! I'm not personally familiar enough with continuations to build that at the moment, but I think I'll do some reading on it over the next few days.

You could implement your program using the model I've suggested like this:

```haskell
go :: String -> String -> Action ()
thing1, thing2 :: IO String
myIO :: IO (Action ())
myIO = do
  x <- async thing1
  y <- async thing2
  (rx, ry) <- waitBoth(x, y)
  return $ go x y

myExtension :: Action ()
myExtension = doAsync myIO
```

It's a bit tougher to read and follow though.

**Comment by mitchellwrosen** [comment]
The problem with that is when the main loop executes the action, it just blocks on `waitBoth`. Right? I might be misunderstanding something.

I was thinking of (roughly) this:


```haskell
data Await a x
  = Await (Async a) (a -> x)

newtype Action a
  = StateT Editor (ReaderT Hooks (FreeT (Await a) IO) a
                                  ^^^^^^^^^^^^^^^

spawn :: IO a -> Action (Async a)
spawn m = liftIO (Control.Concurrent.Async.async m)

await :: Async a -> Action a
await a = liftF (Await a id)
```

Then, the event dispatcher code just puts each `Await a` on some queue, and on each iteration of the event loop, it calls `Control.Concurrent.Async.poll` to see if it's done; if so, run the continuation (synchronously).

**Comment by ChrisPenner** [comment]
Oh cool! Am I understanding this right? So we change Action to have FreeT in the stack, when we unwind (execute) the monad stack we stop when we hit the FreeT and process each Free in turn, then when we hit an async that hasn't finished we just stash it on a queue and keep checking before we move on?

I'm new to the world of Free, but it seems like a good way to go and I'm not opposed to switching to free from monad transformers entirely; I'll just have to fiddle around a bit to see if I can understand everything :)

Another question for you; since FreeT is nested within StateT, we'd apply execStateT before we start unwrapping FreeT right?  Let's say we run `execStateT` with Editor state 'A'; then we start unwrapping the Asyncs in FreeT and find one that hasn't finished yet, we put the whole thing aside until later when the Async is finished, but when we come back later the current state of the editor has changed to state 'B', but the StateT in the partially finished Action was applied with Editor state 'A', if we now finish that action and take its result we lose any changes from state 'B'.

Am I understanding any of that incorrectly? As I said, I'm pretty new to Free, but I find it fascinating and appreciate any explanations you can offer 😁 .


Lastly, I think I may have mis-explained myself, the entire `myIO` block is queued to run asynchronously by the `doAsync` call (which would just add it to a queue), so yes `waitBoth` DOES block, but it blocks inside an already asynchronous execution, so shouldn't block the main thread at all 😁

**Comment by ChrisPenner** [comment]
I believe we can model eventProducers as Producers from the pipes library; there's this nifty lib that Gabriel whipped up: [pipes-concurrency](https://hackage.haskell.org/package/pipes-concurrency-2.0.3/docs/Pipes-Concurrent-Tutorial.html).

I think we might be able to add async actions and event-producers as `Action ()` `Producer`s which run asynchronously, then we can merge the stream of `Action ()`s and just run each one as it comes in. I believe that in this case we'd end up with just one thread per Async event producer, and one for each Async Action.

**Comment by ChrisPenner** [comment]
As for event listeners being parsers over event streams, I think that's actually separate from the async stuff; but we could implement that synchronously inside `dispatchEvent` somehow. I'm thinking we could keep a map of lists of the parsers for each event type and each new event that comes in we'd simply pass it through each parser, collect and run any Actions that are yielded, then push the new parser states back in.

**Comment by ChrisPenner** [comment]
Okay, here's another try, this time using concurrent pipes: https://github.com/ChrisPenner/rasa/pull/14

**Comment by ChrisPenner** [comment]
I think we're in good shape with this now via `asyncEventProviders` and friends.
