### ISSUE TITLE
Key handling of Super/GUI key

### ISSUE THREAD

**Issue by jasonm23** [ChrisPenner/rasa#12]
Modifiers include Shift, Ctrl, Alt at the moment.  Most keyboards support a GUI (Super) key.

I think it would be good if Rasa supports it too.

**Comment by jasonm23** [comment]
(Iirc this would only work outside the terminal)

**Comment by ChrisPenner** [comment]
There's currently no way to run Rasa outside of a terminal, so adding handling for a key it's impossible to press is much more likely to confuse people than be useful.

It's basically a one line change, we'll make it when it comes up.
