### ISSUE TITLE
Cursor is invisible at the end of the line

### ISSUE THREAD

**Issue by robinvd** [ChrisPenner/rasa#16]
If you move the cursor past the last character of a line it becomes invisible

**Comment by ChrisPenner** [comment]
It sure does yup! It has to do with the fact that it's trying to highlight a non-printing character (the new-line) I haven't special-cased it quite yet.

There's a bit of a decision to be made on whether newlines should be 'selectable' at all, for instance you can't select newlines in Vim. Overall not a huge usability issue, but it is pretty annoying. A temporary fix might be to simply tack on an extra space at the end of each line at render time.

**Comment by ChrisPenner** [comment]
Cursor is now visible (https://github.com/ChrisPenner/rasa/commit/ae5f343f88df70733e6db4b5b41fe255f1408459)! It's still really a hack; we'll have to come back and fix this properly and improve the behaviour of commands like `delete` in the future; but at least the cursor doesn't disappear at random anymore.

**Comment by ChrisPenner** [comment]
Should definitely revisit this later; but it's resolved by the hack for now.
