### ISSUE TITLE
Optimizing Multiple-key bindings

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#17]
https://github.com/ChrisPenner/rasa/pull/15 Adds multi-key keymap bindings; however the way it does pattern matching is perhaps sub-optimal. 

It may be possible to optimize it by using some form of 'Keymap tree' and perhaps a [zipper](https://hackage.haskell.org/package/zippers) into that tree; That allows us to traverse our way into the tree while still having an idea of which keys we could possible be waiting for, and allowing us to easily reset and allow us to replay the keypresses that didn't lead to a command when needed.

@robinvd

**Comment by robinvd** [comment]
The problem i have run into so far is that functions like 'f' need a variable to work. As it searched for something not known at compile time.

**Comment by ChrisPenner** [comment]
Closing for now; what we've got is working thanks to @robinvd ; we'll maybe re-open this in the future if it comes up again.
