### ISSUE TITLE
dispatch events from other threads (forkIO)

### ISSUE THREAD

**Issue by clojj** [ChrisPenner/rasa#23]
"... Extensions may also dispatch any kind of event at any time which other extensions may listen for."

Is it save to dispatchEvent from other threads ?

Say in the Main.hs you forkIO before starting the rasa event-loop.
Then (communicating via MVar's) at some point that forked thread wants to deliver a rasa-event.
Is that safe ?

**Comment by ChrisPenner** [comment]
I believe I answered most of this question in the other thread; but as for dispatching events asynchronously, it isn't supported *as part of a `doAsync` call*; but if your extension does have sporadic events it would like to fire you can register an [`eventProvider`](https://github.com/ChrisPenner/rasa/blob/dc13652d41c4c941aa6bca8dcdb55d8d63d74a76/rasa/src/Rasa/Internal/Async.hs#L19) which will do this for you. 

What sort of events are you planning to dispatch asynchronously? It would be possible to build this functionality in (via https://github.com/ChrisPenner/rasa/pull/14/files); but I'd have to revamp that PR as it's too old to merge now.
