### ISSUE TITLE
Lifting Actions inside BufAction

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#31]
`liftAction` is implemented and allows running `Action` inside `BufAction`; but leaves some things to be desired. Currently the idea is that a Buffer is focused alongside the current editor state; any BufActions that affect the buffer affect the 'COPY' of the buffer that's held alongside the editor state without actually effecting the buffer contained inside the Editor state. After executing the `BufAction` the Buffer in the Editor state is replaced with the copy. This allows things to get out of sync in situations where events are dispatched inside a `BufAction` using `liftAction`.

The plan to fix this is to change all lenses which access a buffer through the `HasBuffer` constraint into Lens Traversals; and then to rely on the [`ExceptT` ](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Except.html#t:ExceptT) result from traversals to handle errors if a BufAction deletes the buffer it's operating on, or if something goes funny inside a dispatched action.

Should hopefully work out nicely; but I'm new to ExceptT so we'll see how it goes.

**Comment by clojj** [comment]
Does this impact performance negatively ?

**Comment by ChrisPenner** [comment]
These issues should be fixed now that we've switched to free-monads; let me know if problems persist.
