### ISSUE TITLE
Rethink chosen license

### ISSUE THREAD

**Issue by jgeerds** [ChrisPenner/rasa#34]
Maybe I'm a bit late but I just saw the license discussion [on reddit](https://www.reddit.com/r/haskell/comments/5l0a2i/rasa_modular_texteditor/dbrzyrg/). You mentioned that you don't know the exact differences so I thought it might be a good idea to create this issue as a reminder and to help you out:

["Choose a license"](https://choosealicense.com/) is a nice website which gives you a short comparison of popular licenses.

PS: I would really love to see *rasa* published under GPL 😃

**Comment by ChrisPenner** [comment]
It appears that GPLv3 is incompatible with GPLv2; since we're using yi-rope (which is GPLv2) should we be using GPLv2 for Rasa?

**Comment by siddhanathan** [comment]
@ChrisPenner yi-rope could probably upgrade the license to `GPLv2 or later` if that's a concern.

**Comment by robinvd** [comment]
Doesnt rasa only use it as a library? so licence is no issue.

**Comment by ChrisPenner** [comment]
@robinvd Since we use the library; Rasa is considered a combined work; and therefore must be compatible with the lib.

See here: https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

**Comment by jgeerds** [comment]
Let's wait and see if yi-rope switches to GPLv3

**Comment by robinvd** [comment]
@ChrisPenner huh did not know that, thanks for the link

**Comment by siddhanathan** [comment]
I just realized GPLv2 on cabal seems to imply v2 or later. So I think we can close this issue.

**Comment by ChrisPenner** [comment]
Sounds good; Rasa is now GPLv3 with the exception of the `text-lens` library (which is independent of yi-rope); I'll publish the new versions to Hackage ASAP.

Thanks for your help and co-operation on this everyone!
