### ISSUE TITLE
Typing at the start of a line deletes the previous line.

### ISSUE THREAD

**Issue by robinvd** [ChrisPenner/rasa#37]

**Comment by ChrisPenner** [comment]
I believe this was fixed in https://github.com/ChrisPenner/rasa/commit/07743ed9f9fc2b535632bba5c334cf884c13a8f7; Can you reproduce this on current master?

Make sure you're merging in upstream to your fork 😁 👍 

We can re-open this if you can give me a reproducible case on master; thanks!

**Comment by robinvd** [comment]
Yea you are right, i thought i was on the current master while submitting this issue. Sorry for the useless issue. Glad it is fixed
