### ISSUE TITLE
seg fault when running after build

### ISSUE THREAD

**Issue by holtzermann17** [ChrisPenner/rasa#56]
Hi, I've just built rasa.  It looks like it built and ran itself correctly, see [this gist](https://gist.github.com/holtzermann17/3353d8f919384c69b4d2e79a33c34a33).  However, when I run the following in a terminal I get a segfault.

> **$ stack exec rasa**
> /private/var/folders/r0/n2zx9x5571g_5k9r6z4mgd5c0000gn/T/nix-shell-43946-0/rc: line 1: 44777 Segmentation fault: 11  '/usr/local/Cellar/haskell-stack/1.7.1/bin/stack' $STACK_IN_NIX_EXTRA_ARGS '--internal-re-exec-version=1.7.1' 'exec' 'rasa'

I'm on Mac OS 10.13.6, ghc 8.4.3.   As advised, stack.yaml includes these lines:

```
extra-lib-dirs:
- /usr/local/opt/icu4c/lib 
extra-include-dirs:
- /usr/local/opt/icu4c/include
```

**Comment by ChrisPenner** [comment]
I'm afraid I can't reproduce this; we recently upgraded to a much more recent LTS; maybe try again on latest master and see if that helps?
