### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by clojj** [ChrisPenner/rasa#58]
using lts-10.7

![rasa-build](https://user-images.githubusercontent.com/4367963/48093837-bba05080-e210-11e8-86de-971546dbe840.png)

**Comment by jmatsushita** [comment]
Have you tried this in your `stack.yml`?:
```
extra-deps:
- vty-5.25
```

**Comment by jmatsushita** [comment]
Oh actually, I realize I had to patch `rasa-ext-slate` to fit the updated api of `vty` which added a `Url` attribute to its interface. I'll post a couple of PRs.

**Comment by jmatsushita** [comment]
PR submitted and merged! Let us know if this is solved!

**Comment by ChrisPenner** [comment]
Should be solved with #59 😄
