### ISSUE TITLE
Standardize Rendering Preferences

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#8]
Rasa doesn't have an 'official' renderer, the extension interface is empowered to allow people to write their own renderer's if they desire. (Though [Slate](https://github.com/ChrisPenner/rasa/tree/master/rasa-ext-slate) is currently the primary renderer out there, consider it a reference implementation).

That said, there's certainly value in having a standardized way for non-rendering extensions to express their rendering desires; e.g. overlay, minibar on the bottom, side-panel, currently hidden etc.

It would be great if extensions could implement some standard 'renderable' interface which would be exposed to extensions that do rendering.

Some things this will *probably* want to cover:

- Window sizing/placement
- Scrolling/viewports
- Overlays (for auto-complete, etc.)
- Window Dependencies (e.g. this buffer displays info about this other buffer, so they should be displayed together.
- Support the idea of having multiple views into the same buffer.
- Be viewport size agnostic (let the renderer make these decisions, just express preferences)

This issue is for discussing features that should be covered by the standard and how they should be implemented.

**Comment by ChrisPenner** [comment]
Hrmm, this one's a bit of a tricky problem, I'd really like to leave any notion of `windows` or `tabs` outside of the core, but means that all viewport related things must be application specific, including scrolling. I'd love to find a way to make at least scrolling generic, possibly viewports in general so that they may be shared by multiple renderers; so it'll take some figuring to find something general enough.

**Comment by ChrisPenner** [comment]
Implemented in https://github.com/ChrisPenner/rasa/pull/19

**Comment by DarwinSenior** [comment]
I have just discovered your project and I really like to help. 
I recently played around and implemented a frontend for Neovim with Electron according to their [reference][1] , and mainly this [specification][2].

They have a nice protocol and after a weekend it is already usable, but I am also aware that there is a [new idea that called smart ui][3] that seems very nice and plausible. This sounds promising and I think it worth trying.
 

[1]: https://github.com/neovim/neovim/wiki/Plugin-UI-architecture
[2]: https://neovim.io/doc/user/msgpack_rpc.html#rpc-remote-ui
[3]: http://tarruda.github.io/articles/neovim-smart-ui-protocol/

**Comment by ChrisPenner** [comment]
@DarwinSenior Interesting stuff! A key part of Rasa is its extensibility; so I definitely want this sort of thing to be possible! In fact Rasa already seems to be following many of the principles presented in that article about a 'smart ui'; the implementation, behaviour, and display are all decoupled and can be replaced as modules.

I'm unsure at this point whether Rasa should support a given format specifically; or just enable users to build extensions for any format they wish. I lean towards the latter; and I believe that with the current API it'd be possible to implement a msgpack interface simply by adding a few event converters and coming up with a good representation of the buffers. Performance for this sort of thing should be relatively similar to performance possible by a first-class implementation.

I'd definitely like to support you if you'd like to create an extension for something like this; so please let me know if you need a hand with anything in the [Chat Room](https://gitter.im/rasa-editor/Lobby) and I'll help however I can! If you find something difficult to do from the extension interface I'll work towards adding combinators or tools to allow it to be possible!

If you just want to chat about possibilities, send me a message on the [gitter chat](https://gitter.im/rasa-editor/Lobby), I'd love to talk about it!
